version: '3.9'

services:
  server:
    container_name: server
    image: server:0.0.1
    build:
      context: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      DEV_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    networks:
      - shared-network
    volumes:
      - .:/app/server
      - /app/server/node_modules
    depends_on:
      - database

  database:
    container_name: agro_input_db 
    image: "postgres"
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - shared-network
    volumes:
      - vol-data:/var/lib/postgresql/data
volumes:
  vol-data:
networks:
  shared-network: